DROP SEQUENCE SEQ_TIPO_ROPA;
CREATE SEQUENCE SEQ_TIPO_ROPA START WITH 100 INCREMENT BY 1;

DROP SEQUENCE SEQ_CATEGORIA;
CREATE SEQUENCE SEQ_CATEGORIA START WITH 100 INCREMENT BY 1;

DROP SEQUENCE STOCK_SEQ;
CREATE SEQUENCE STOCK_SEQ START WITH 100 INCREMENT BY 1;