server:
  port: 8761

spring:
  application:
    name: ms_eureka
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/
    register-with-eureka: false
    fetch-registry: false