version: '3.8'

services:
  # ==========================================
  # 1. INFRAESTRUCTURA CORE
  # ==========================================
  ms-eureka:
    build: ./ms_eureka
    container_name: contenedor-eureka
    ports:
      - "8761:8761"

  ms-api:
    build: ./ms_api
    container_name: contenedor-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ms-eureka

  # ==========================================
  # 2. MICROSERVICIOS DE NEGOCIO
  # ==========================================
  ms-cliente:
    build: ./ms-cliente
    container_name: contenedor-cliente
    ports:
      - "8095:8095"
    volumes:
      - ./WalletDeBaseDeDatos:/opt/oracle/wallet
    depends_on:
      - ms-eureka

  ms-empresa:
    build: ./ms-empresa
    container_name: contenedor-empresa
    ports:
      - "8089:8089"
    volumes:
      - ./WalletDeBaseDeDatos:/opt/oracle/wallet
    depends_on:
      - ms-eureka

  ms-envios:
    build: ./ms-envios
    container_name: contenedor-envios
    ports:
      - "8084:8084"
    volumes:
      - ./WalletDeBaseDeDatos:/opt/oracle/wallet
    depends_on:
      - ms-eureka

  ms-inventario:
    build: ./ms-inventario
    container_name: contenedor-inventario
    ports:
      - "8086:8086"
    volumes:
      - ./WalletDeBaseDeDatos:/opt/oracle/wallet
    depends_on:
      - ms-eureka

  ms-ventas:
    build: ./ms-ventas
    container_name: contenedor-ventas
    ports:
      - "8092:8092"
    volumes:
      - ./WalletDeBaseDeDatos:/opt/oracle/wallet
    depends_on:
      - ms-eureka