server:
  port: 8084

spring:
  application:
    name: ms-envios

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@wave6mvvwt38qrkd_high?TNS_ADMIN=/opt/oracle/wallet
    username: ADMIN
    password: FullStack-001
    hikari:
      maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    schemas: ADMIN
    default-schema: ADMIN
    out-of-order: true
    url: jdbc:oracle:thin:@wave6mvvwt38qrkd_high?TNS_ADMIN=/opt/oracle/wallet
    user: ADMIN
    password: FullStack-001
    table: flyway_schema_history_envios

eureka:
  client:
    service-url:
      defaultZone: http://ms-eureka:8761/eureka/

logging:
  level:
    org:
      hibernate: DEBUG
      flywaydb: DEBUG